import { splitEqualCents } from './money-math';
import type { Bill, Expense, HouseholdMember, RecurringBillTemplate, Settlement } from './types';

// Local mock data only — no backend yet. See the note in types.ts: this
// member list is intentionally separate from Kitchen's for Milestone 4.

function isoDaysFromToday(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

export const householdMembers: HouseholdMember[] = [
  { id: 'you', name: 'You', isCurrentUser: true },
  { id: 'bella', name: 'Bella', initials: 'B', isCurrentUser: false },
  { id: 'karyn', name: 'Karyn', initials: 'K', isCurrentUser: false },
  { id: 'nat', name: 'Nat', initials: 'N', isCurrentUser: false },
];

export const expenses: Expense[] = [
  {
    id: 'expense-1',
    description: 'Costco run',
    amountCents: 9642,
    category: 'groceries',
    paidByMemberId: 'you',
    date: isoDaysFromToday(-6),
    participants: ['you', 'bella', 'nat'],
    splitMode: 'equal',
    shares: splitEqualCents(9642, ['you', 'bella', 'nat']),
    createdAt: isoDaysFromToday(-6),
    updatedAt: isoDaysFromToday(-6),
  },
  {
    id: 'expense-2',
    description: 'Gas',
    amountCents: 6000,
    category: 'transportation',
    paidByMemberId: 'karyn',
    date: isoDaysFromToday(-5),
    participants: ['you', 'karyn'],
    splitMode: 'equal',
    shares: splitEqualCents(6000, ['you', 'karyn']),
    createdAt: isoDaysFromToday(-5),
    updatedAt: isoDaysFromToday(-5),
  },
  {
    id: 'expense-3',
    description: 'Dish soap + paper towels',
    amountCents: 1870,
    category: 'household_supplies',
    paidByMemberId: 'you',
    date: isoDaysFromToday(-4),
    participants: ['you', 'bella', 'karyn', 'nat'],
    splitMode: 'equal',
    shares: splitEqualCents(1870, ['you', 'bella', 'karyn', 'nat']),
    createdAt: isoDaysFromToday(-4),
    updatedAt: isoDaysFromToday(-4),
  },
  {
    id: 'expense-4',
    description: 'Pizza night',
    amountCents: 4200,
    category: 'dining',
    paidByMemberId: 'nat',
    date: isoDaysFromToday(-2),
    participants: ['you', 'bella', 'nat'],
    splitMode: 'equal',
    shares: splitEqualCents(4200, ['you', 'bella', 'nat']),
    createdAt: isoDaysFromToday(-2),
    updatedAt: isoDaysFromToday(-2),
  },
  // Generated by paying last month's Internet bill (see `bills` below) —
  // this is what actually creates the corresponding debt, not the bill
  // itself. See the `linkedExpenseId` on bill-1.
  {
    id: 'expense-5',
    description: 'Internet',
    amountCents: 6400,
    category: 'utilities',
    paidByMemberId: 'you',
    date: isoDaysFromToday(-24),
    participants: ['you', 'bella', 'karyn', 'nat'],
    splitMode: 'equal',
    shares: splitEqualCents(6400, ['you', 'bella', 'karyn', 'nat']),
    notes: 'Internet — paid bill',
    createdAt: isoDaysFromToday(-24),
    updatedAt: isoDaysFromToday(-24),
  },
];

export const settlements: Settlement[] = [
  {
    id: 'settlement-1',
    fromMemberId: 'bella',
    toMemberId: 'you',
    amountCents: 1500,
    date: isoDaysFromToday(-1),
    createdAt: isoDaysFromToday(-1),
  },
];

export const recurringBills: RecurringBillTemplate[] = [
  {
    id: 'recurring-internet',
    name: 'Internet',
    amountCents: 6400,
    dayOfMonth: 5,
    responsibleMemberId: 'you',
    participants: ['you', 'bella', 'karyn', 'nat'],
    splitMode: 'equal',
    createdAt: isoDaysFromToday(-54),
  },
];

export const bills: Bill[] = [
  {
    id: 'bill-1',
    name: 'Internet',
    amountCents: 6400,
    dueDate: isoDaysFromToday(-24),
    responsibleMemberId: 'you',
    participants: ['you', 'bella', 'karyn', 'nat'],
    splitMode: 'equal',
    shares: splitEqualCents(6400, ['you', 'bella', 'karyn', 'nat']),
    recurrence: 'monthly',
    recurringBillId: 'recurring-internet',
    status: 'paid',
    paidAt: isoDaysFromToday(-24),
    linkedExpenseId: 'expense-5',
    createdAt: isoDaysFromToday(-24),
    updatedAt: isoDaysFromToday(-24),
  },
  {
    id: 'bill-2',
    name: 'Internet',
    amountCents: 6400,
    dueDate: isoDaysFromToday(3),
    responsibleMemberId: 'you',
    participants: ['you', 'bella', 'karyn', 'nat'],
    splitMode: 'equal',
    shares: splitEqualCents(6400, ['you', 'bella', 'karyn', 'nat']),
    recurrence: 'monthly',
    recurringBillId: 'recurring-internet',
    status: 'upcoming',
    createdAt: isoDaysFromToday(-1),
    updatedAt: isoDaysFromToday(-1),
  },
  {
    id: 'bill-3',
    name: 'Electric',
    amountCents: 8850,
    dueDate: isoDaysFromToday(5),
    participants: ['you', 'bella', 'karyn', 'nat'],
    splitMode: 'equal',
    shares: splitEqualCents(8850, ['you', 'bella', 'karyn', 'nat']),
    recurrence: 'one_time',
    status: 'upcoming',
    createdAt: isoDaysFromToday(-2),
    updatedAt: isoDaysFromToday(-2),
  },
];
