// -----------------------------------------------------------------------------
// Household members
//
// `HouseholdMember` now lives in src/features/household/types.ts — the one
// canonical member source shared by Kitchen, Money, and Tasks (as of
// Milestone 5). Money no longer defines or stores its own copy; import the
// type from '@/features/household/types' instead.
// -----------------------------------------------------------------------------
// Shared shape for "how much of this does each participant owe"
// -----------------------------------------------------------------------------

/**
 * 'equal' covers both "split among everyone" and "split among selected
 * roommates" — those are the same mechanism (equal division of whichever
 * participants are chosen), so there's no separate mode for each. `shares`
 * is always resolved and stored at save time regardless of mode, which is
 * what keeps history immutable and leaves room for a future 'percentage'
 * mode to be a pure UI addition later — same stored shape, no migration.
 */
export type SplitMode = 'equal' | 'custom';

export type ParticipantShare = {
  memberId: string;
  amountCents: number;
};

export type ExpenseCategory =
  | 'groceries'
  | 'household_supplies'
  | 'utilities'
  | 'dining'
  | 'transportation'
  /** Used exclusively for the Expense generated by `markBillPaid` — keeps bill-driven debt visually distinct in activity/history from a manually-added expense. */
  | 'bill'
  | 'other';

// -----------------------------------------------------------------------------
// Expenses
//
// Designed so a future receipt-scanning workflow can call `addExpense` with a
// plain input directly — Money has no dependency on Kitchen, so that future
// workflow (not built yet) would create Kitchen inventory items and a Money
// expense side by side from the same scan, not through any link between the
// two feature domains.
// -----------------------------------------------------------------------------

export type Expense = {
  id: string;
  description: string;
  amountCents: number;
  category: ExpenseCategory;
  paidByMemberId: string;
  /** ISO date string (yyyy-mm-dd). */
  date: string;
  participants: string[];
  splitMode: SplitMode;
  /** Resolved at creation time and never recalculated — preserves history even if household membership changes later. */
  shares: ParticipantShare[];
  notes?: string;
  createdAt: string;
  updatedAt: string;
};

export type NewExpenseInput = {
  description: string;
  amountCents: number;
  category: ExpenseCategory;
  paidByMemberId: string;
  date: string;
  participants: string[];
  splitMode: SplitMode;
  shares: ParticipantShare[];
  notes?: string;
};

// -----------------------------------------------------------------------------
// Settlements — one roommate recording a payment to another. HouseholdOS
// never moves money; this only records that a payment happened so balances
// can reflect it.
// -----------------------------------------------------------------------------

export type Settlement = {
  id: string;
  fromMemberId: string;
  toMemberId: string;
  amountCents: number;
  date: string;
  note?: string;
  createdAt: string;
};

export type NewSettlementInput = {
  fromMemberId: string;
  toMemberId: string;
  amountCents: number;
  date: string;
  note?: string;
};

// -----------------------------------------------------------------------------
// Bills
//
// A Bill in 'upcoming' status is deliberately invisible to the balance
// engine — balances are derived only from Expense + Settlement records, so
// an unpaid bill can never falsely suggest anyone owes anyone money. Marking
// a bill paid creates exactly one Expense (see store.ts `markBillPaid`,
// guarded by `status`, so repeating the action is a no-op) and links back to
// it via `linkedExpenseId`. That generated Expense's `paidByMemberId` is the
// single source of truth for "who actually paid" — the Bill itself doesn't
// duplicate that fact.
// -----------------------------------------------------------------------------

export type BillRecurrence = 'one_time' | 'monthly';

export type BillStatus = 'upcoming' | 'paid';

export type Bill = {
  id: string;
  name: string;
  amountCents: number;
  /** ISO date string (yyyy-mm-dd). */
  dueDate: string;
  /** The person expected to handle this bill — distinct from who actually paid it, which lives on the linked Expense once paid. */
  responsibleMemberId?: string;
  participants: string[];
  splitMode: SplitMode;
  shares: ParticipantShare[];
  recurrence: BillRecurrence;
  /** Set when this occurrence was generated from a RecurringBillTemplate. */
  recurringBillId?: string;
  status: BillStatus;
  paidAt?: string;
  /** Set once paid — the Expense that represents this bill's actual debt. */
  linkedExpenseId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
};

export type NewBillInput = {
  name: string;
  amountCents: number;
  dueDate: string;
  responsibleMemberId?: string;
  participants: string[];
  splitMode: SplitMode;
  shares: ParticipantShare[];
  recurrence: BillRecurrence;
  notes?: string;
};

/**
 * The reusable monthly "setup." Each month's Bill is its own record pointing
 * back here via `recurringBillId`, so "Internet — June/July/August" are
 * distinct occurrences under one template, not one row being overwritten.
 * No scheduler reads this — occurrences are generated on demand (see
 * `generateNextOccurrence` in store.ts), never automatically.
 */
export type RecurringBillTemplate = {
  id: string;
  name: string;
  amountCents: number;
  /** Day of month the bill is due, 1-28 (kept simple — no month-end edge cases). */
  dayOfMonth: number;
  responsibleMemberId?: string;
  participants: string[];
  splitMode: SplitMode;
  notes?: string;
  createdAt: string;
};

// -----------------------------------------------------------------------------
// Derived views (not stored — produced by activity.ts from the records above)
// -----------------------------------------------------------------------------

export type ActivityEntry =
  | { type: 'expense_added'; id: string; date: string; expense: Expense }
  | { type: 'settlement'; id: string; date: string; settlement: Settlement }
  | { type: 'bill_added'; id: string; date: string; bill: Bill }
  | { type: 'bill_paid'; id: string; date: string; bill: Bill };
